sbatch slurm/tinyimagenet_usresnet56x25.sh
sbatch slurm/tinyimagenet_usresnet56x50.sh
sbatch slurm/tinyimagenet_usresnet56x75.sh
sbatch slurm/tinyimagenet_usresnet56x100.sh

sbatch slurm/tinyimagenet_usvgg16_bn_x25.sh
sbatch slurm/tinyimagenet_usvgg16_bn_x50.sh
sbatch slurm/tinyimagenet_usvgg16_bn_x75.sh
sbatch slurm/tinyimagenet_usvgg16_bn_x100.sh